# Workflow to run a Flask application on GitHub Actions
# This workflow installs dependencies and starts the Flask development server

name: Run Flask App

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-flask:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure environment
        run: |
          echo "FLASK_APP=app.py" >> $GITHUB_ENV     # Replace 'app.py' with your entrypoint
          echo "FLASK_ENV=development" >> $GITHUB_ENV

      - name: Run Flask server
        run: flask run --host=0.0.0.0 --port=5000
        # This command will keep the job running until manually cancelled or times out
